# Generated by Django 2.2 on 2021-07-08 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Transgender'), ('4', 'Unknown')], max_length=2, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('1', 'A +'), ('2', 'A -'), ('3', 'B +'), ('4', 'B -'), ('5', 'O +'), ('6', 'O -'), ('7', 'AB +'), ('8', 'AB -')], max_length=2, null=True)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('prescription', models.CharField(blank=True, max_length=500, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.Doctor')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Hospital')),
            ],
        ),
    ]
